server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/alterra?createDatabaseIfNotExist=true
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      host: localhost
      port: 27017
      database: logging
      username: root
      password: rootpassword
      authentication-database: admin
